### PR TITLE
Add hotkeys for solid modeling capability

### PR DESCRIPTION
**Pull request by AnonymousPrayers**
Gigs himself guaranteed an auto-approval for this lol. Supplies hotkeys (without buttons because idk how the GUI works yet) for unioning, separating, and negating, and I got the history into the union but it's 1:20am so I didn't try to figure it out yet for separate and I'm too lazy to do it right now for negate.

### CODE REVIEW

**Comment by GigsD4X** [comment]
Wait what? If this is only available in plugins, that means it's only available in Studio! Which means that it'd be redundant to include it in BT!

**Comment by AnonymousPrayers** [comment]
You didn't know that? Having it in BT would be infinitely more convenient, as we don't have to switch plugins and mess with the selection to use unions. You did already say you'd approve it right away.



On Thu, May 14, 2015 at 8:30 PM -0700, "Robert" <notifications@github.com> wrote:
Wait what? If this is only available in plugins, that means it's only available in Studio! Which means that it'd be redundant to include it in BT!

---

**Comment by GigsD4X** [comment]
Don't you just have to right click?

**Comment by AnonymousPrayers** [comment]
It messes up the selection that way.




On Thu, May 14, 2015 at 9:00 PM -0700, "Robert" <notifications@github.com> wrote:
Don't you just have to right click?
On May 14, 2015 8:44 PM, "Zenon" <notifications@github.com> wrote:

> You didn't know that? Having it in BT would be infinitely more convenient,
> as we don't have to switch plugins and mess with the selection to use
> unions. You did already say you'd approve it right away.
>
>
>
> On Thu, May 14, 2015 at 8:30 PM -0700, "Robert" <notifications@github.com>
> wrote:
> Wait what? If this is only available in plugins, that means it's only
> available in Studio! Which means that it'd be redundant to include it in BT!
>
> ---
> Reply to this email directly or view it on GitHub:
>
> https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102243339
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102245245>
> .
>


---

**Comment by GigsD4X** [comment]
Alright we can do this then :D I'll make a few code changes and pull this
in :-)

**Comment by AnonymousPrayers** [comment]
Yays thankyou





On Thu, May 14, 2015 at 9:08 PM -0700, "Robert" <notifications@github.com> wrote:
Alright we can do this then :D I'll make a few code changes and pull this
in :-)
On May 14, 2015 9:03 PM, "Zenon" <notifications@github.com> wrote:

> It messes up the selection that way.
>
>
>
>
> On Thu, May 14, 2015 at 9:00 PM -0700, "Robert" <notifications@github.com>
> wrote:
> Don't you just have to right click?
> On May 14, 2015 8:44 PM, "Zenon" <notifications@github.com> wrote:
>
> > You didn't know that? Having it in BT would be infinitely more
> convenient,
> > as we don't have to switch plugins and mess with the selection to use
> > unions. You did already say you'd approve it right away.
> >
> >
> >
> > On Thu, May 14, 2015 at 8:30 PM -0700, "Robert" <
> notifications@github.com>
> > wrote:
> > Wait what? If this is only available in plugins, that means it's only
> > available in Studio! Which means that it'd be redundant to include it in
> BT!
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> >
> https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102243339
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102245245
> >
> > .
> >
>
>
> ---
> Reply to this email directly or view it on GitHub:
>
> https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102247013
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/F3XTeam/ROBLOX-Building-Tools/pull/57#issuecomment-102247712>
> .
>


---

**Pull request closed without merging**
